name: SemVer parse test

on: [push]

jobs:
  echo-if-ref-is-semver:
    runs-on: ubuntu-latest
    name: Parse GITHUB_REF_NAME for SemVer
    steps:
      - name: Output github.ref
        run: echo "${{ github.ref }}"
      - name: Parse GitHub ref
        id: parse
        uses: NetChris/parse-semver@5-make-parsing-find-the-first-occurrence-of-the-semver-pattern
        with:
          value_to_parse: '${{ github.ref }}'
      - name: Output full match
        run: echo "${{ steps.parse.outputs.semver_version }}"
      - name: Output major
        run: echo ${{ steps.parse.outputs.major_version }}
      - name: Output minor
        run: echo ${{ steps.parse.outputs.minor_version }}
      - name: Output patch
        run: echo ${{ steps.parse.outputs.patch_version }}
      - name: Output prerelease
        run: echo ${{ steps.parse.outputs.pre_release_version }}
      - name: Output buildmetadata
        run: echo ${{ steps.parse.outputs.build_metadata }}
      - name: Output major_minor_version
        run: echo ${{ steps.parse.outputs.major_minor_version }}
      - name: Major/Minor detected?
        if: ${{ steps.parse.outputs.major_minor_version != '' }}
        run: echo "${{ steps.parse.outputs.major_minor_version }}"
      - name: has_semver_version?
        if: ${{ steps.parse.outputs.has_semver_version }}
        run: echo "${{ steps.parse.outputs.has_semver_version }}"
